version: 1.0.{build}

before_build:
  - cmd: nuget restore

build:
  project: YAGLi.sln
  verbosity: detailed

environment:
  COVERALLS_REPO_TOKEN:
    secure: 3cbofsGHnBMS8iG+QvluRYYGK0cPr941ITq+Jxy8ZoGCXFWCQU3Xr73nMNwj4ccx

after_test: 
# generate report for NUnit testing framework:
  - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.2.1\tools\nunit3-console.exe" -targetargs:"/domain:single YAGLi.Tests/bin/debug/YAGLi.Tests.dll" -output:coverage.xml

# generate report for MSTest testing framework:
  - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%